def n_plus_1 (n) :
    result = n + 1

n_plus_1(3)
#print (result)
# 결과 에러 발생 함수에서의 변수는 함수 밖에서 쓸수없다.